### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [rxavier/econuy#5]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.7.3. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary econuy -w /tmp/ext econuy==0.7.3
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting econuy==0.7.3
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/d30/e8e6efdb40edc/econuy-0.7.3.tar.gz (42 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-ooi5dob3/econuy/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-ooi5dob3/econuy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-ooi5dob3/econuy/pip-egg-info
         cwd: /tmp/pip-wheel-ooi5dob3/econuy/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-ooi5dob3/econuy/setup.py", line 18, in <module>
        pipfile_lock_requirements = get_requirements_from_pipfile_lock()
      File "/tmp/pip-wheel-ooi5dob3/econuy/setup.py", line 12, in get_requirements_from_pipfile_lock
        lock_data = json.load(open(pipfile_lock))
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-wheel-ooi5dob3/econuy/Pipfile.lock'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by rxavier** [comment]
Thanks!
